services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
    container_name: lagoa-ged
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - /dados/PMLS/film:/var/www/html/storage/documentos
    env_file:
      - .env
    depends_on:
      - mongodb_prod
      - redis_prod
      
  mongodb_prod:
    image: mongo:latest
    container_name: lagoa_mongo
    restart: always
    ports:
      - "65017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      # VOLUME COM OS DADOS RECUPERADOS - 206.695 documentos + 5 usuários + 6 grupos
      - "1a2b404226a906447d3c05931a3910a5250429059d578c61ab025d1336adde31:/data/db"
    env_file:
      - .env
  
  redis_prod:
    image: redis/redis-stack-server:latest
    container_name: lagoa_redis
    restart: always
    ports:
      - "6679:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env

volumes:
  1a2b404226a906447d3c05931a3910a5250429059d578c61ab025d1336adde31:
    external: true